### ISSUE TITLE
CUDA driver version and runtime version conflict issue.

### ISSUE THREAD

**Issue by lllkiller-jlll** [Xilinx/Vitis-AI#111]
Hi. I'm trying to train SSD model with vitis ai.

I refered Vitis AI Tutorial [https://github.com/Xilinx/Vitis-AI-Tutorials/tree/VAI-Caffe-SSD-Tutorial](url).

But I'm faced with cuda version conflict isseu.

The message is below:
`
>   -solver solver.prototxt \
>   -weights VGG_ILSVRC_16_layers_fc_reduced.caffemodel \
>   -gpu 0 2>&1 | tee SSD_train.log
tee: SSD_train.log: Permission denied
F0706 02:28:39.882016    43 gpu_memory.cpp:187] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***
    @     0x7f0e088a54dd  google::LogMessage::Fail()
    @     0x7f0e088ad071  google::LogMessage::SendToLog()
    @     0x7f0e088a4ecd  google::LogMessage::Flush()
    @     0x7f0e088a676a  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f0e075b6d45  caffe::GPUMemory::Manager::update_dev_info()
    @     0x7f0e075b72bf  caffe::GPUMemory::Manager::init()
    @     0x55e2568350cd  train()
    @     0x55e25682ea49  main
    @     0x7f0e05cc0b97  __libc_start_main
    @     0x55e25682f689  (unknown)
`

How can I fix it?

Thanks.

**Comment by lllkiller-jlll** [comment]
I installed nvidia driver 410.78 and cuda 10.0 in my system.

**Comment by lllkiller-jlll** [comment]
I solved this issue.

I launched docker using image's name instead of image's id.
