### ISSUE TITLE
Vitis-AI-Tensorflow2 GPU docker report CUDA_ERROR_NO_DEVICE

### ISSUE THREAD

**Issue by eerobert** [Xilinx/Vitis-AI#261]
I have a 1080ti GPU card and compile gpu docker successfully on ubuntu18.04

inside the docker/conda i can run nvidia-smi without problem.

but when i run run_eval_images_by_h5 for tf2_resnet50, it reports failed to call cuinit
same symptom also encounter when running tf_resnetv1_50

any help? thanks

driver version: 418.113
cuda version: 10.1
cudnn version: 7.6.5

**Comment by lji72** [comment]
It seems that the issue is caused by gpu assignment. How many gpus are in your server?  you can modify gpu from 1 to 0 in run_eval_images_by_h5.sh.

**Comment by eerobert** [comment]
thanks. it works.
