### ISSUE TITLE
pytorch - RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by haipnh** [Xilinx/Vitis-AI#822]
Hi,

I'm examining the pt_fadnet_sceneflow_576_960_441G_2.0, downloaded by `python3 downloader.py`.

My system:
Ubuntu 18.04
RTX 3080Ti

After successfully building the docker image xilinx/vitis-ai-gpu:2.0.0.1103, I executed 
```
./docker_run.sh xilinx/vitis-ai-gpu:latest
conda activate vitis-ai-pytorch
cd models/AI-Model-Zoo/pt_fadnet_sceneflow_576_960_441G_2.0
pip3 install --user -r requirements.txt
```
After that, I launched python to have a quick test
```
import torch
torch.version.cuda # 10.2
torch.cuda.is_available() # True
```
However, when I launched `bash run_demo.sh`, it returned
```
2022-05-31 08:41:36,005 [font_manager.py:1423] INFO Generating new fontManager, this may take some time...
2022-05-31 08:41:36,366 [main.py:134] INFO Configurations: Namespace(augment=0, batch_size=1, beta=0.999, cuda=True, datapath='../data', dataset='sceneflow', demo=1, devices='0', eval=1, flowDiv=1.0, logFile='logs/fadnet_sceneflow_test_demo.log', loss='loss_configs/test.json', lr=0.0002, manualSeed=None, maxdisp=-1, model='../float/model_best_single.pth', momentum=0.9, net='fadnet', outf='.', showFreq=100, startEpoch=0, startRound=0, trainlist='lists/SceneFlow.list', vallist='lists/FlyingThings3D_release_TEST.list', workers=8)
2022-05-31 08:41:36,367 [main.py:138] INFO Random Seed: 51
2022-05-31 08:41:36,377 [main.py:47] INFO [[0.32, 0.16, 0.08, 0.04, 0.02, 0.01, 0.005]]
2022-05-31 08:41:36,378 [dltrainer.py:66] INFO Use 16 processes to load data...
Traceback (most recent call last):
  File "main.py", line 146, in <module>
    main(opt)
  File "main.py", line 50, in main
    trainer = DisparityTrainer(opt.net, opt.lr, opt.devices, opt.dataset, opt.trainlist, opt.vallist, opt.datapath, opt.batch_size, opt.maxdisp, opt.demo, opt.model)
  File "/workspace/models/AI-Model-Zoo/pt_fadnet_sceneflow_576_960_441G_2.0/code/dltrainer.py", line 53, in __init__
    self.initialize()
  File "/workspace/models/AI-Model-Zoo/pt_fadnet_sceneflow_576_960_441G_2.0/code/dltrainer.py", line 115, in initialize
    self._build_net()
  File "/workspace/models/AI-Model-Zoo/pt_fadnet_sceneflow_576_960_441G_2.0/code/dltrainer.py", line 90, in _build_net
    self.net.cuda()
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 463, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 463, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
```

I have no idea to solve this problem and ask for some help.
Thank you in advance.

**Comment by haipnh** [comment]
I tried on other machine, it has the same issue.

```shell
(vitis-ai-pytorch) Vitis-AI /workspace/models/AI-Model-Zoo/pt_fadnet_sceneflow_576_960_441G_2.0 > python -c "import torch; print(torch.version.cuda); print(torch.cuda.is_available()); print(torch.cuda.device_count()); print(torch.cuda.get_device_name(0))"
10.1
True
1
NVIDIA GeForce GTX 1080 Ti
(vitis-ai-pytorch) Vitis-AI /workspace/models/AI-Model-Zoo/pt_fadnet_sceneflow_576_960_441G_2.0 > cd code/
(vitis-ai-pytorch) Vitis-AI /workspace/models/AI-Model-Zoo/pt_fadnet_sceneflow_576_960_441G_2.0/code > ./run_demo.sh 
2022-06-02 06:58:51,699 [font_manager.py:1423] INFO Generating new fontManager, this may take some time...
2022-06-02 06:58:52,084 [main.py:99] INFO Torch version: 1.4.0
2022-06-02 06:58:52,088 [main.py:100] INFO CUDA available: False
2022-06-02 06:58:52,090 [main.py:137] INFO Configurations: Namespace(augment=0, batch_size=1, beta=0.999, cuda=True, datapath='../data', dataset='sceneflow', demo=1, devices='0', eval=1, flowDiv=1.0, logFile='logs/fadnet_sceneflow_test_demo.log', loss='loss_configs/test.json', lr=0.0002, manualSeed=None, maxdisp=-1, model='../float/model_best_single.pth', momentum=0.9, net='fadnet', outf='.', showFreq=100, startEpoch=0, startRound=0, trainlist='lists/SceneFlow.list', vallist='lists/FlyingThings3D_release_TEST.list', workers=8)
2022-06-02 06:58:52,091 [main.py:141] INFO Random Seed: 7131
2022-06-02 06:58:52,092 [main.py:47] INFO [[0.32, 0.16, 0.08, 0.04, 0.02, 0.01, 0.005]]
2022-06-02 06:58:52,115 [dltrainer.py:66] INFO Use 16 processes to load data...
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=50 error=100 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "main.py", line 149, in <module>
    main(opt)
  File "main.py", line 50, in main
    trainer = DisparityTrainer(opt.net, opt.lr, opt.devices, opt.dataset, opt.trainlist, opt.vallist, opt.datapath, opt.batch_size, opt.maxdisp, opt.demo, opt.model)
  File "/workspace/models/AI-Model-Zoo/pt_fadnet_sceneflow_576_960_441G_2.0/code/dltrainer.py", line 53, in __init__
    self.initialize()
  File "/workspace/models/AI-Model-Zoo/pt_fadnet_sceneflow_576_960_441G_2.0/code/dltrainer.py", line 115, in initialize
    self._build_net()
  File "/workspace/models/AI-Model-Zoo/pt_fadnet_sceneflow_576_960_441G_2.0/code/dltrainer.py", line 90, in _build_net
    self.net.cuda()
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 304, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 223, in _apply
```

**Comment by haipnh** [comment]
I tried on other machine, it has the same issue

```shell
(vitis-ai-pytorch) Vitis-AI /workspace/models/AI-Model-Zoo/pt_fadnet_sceneflow_576_960_441G_2.0/code > python -c "import torch; print(torch.version.cuda); print(torch.cuda.is_available()); print(torch.cuda.device_count()); print(torch.cuda.get_device_name(0))"
10.1
True
1
NVIDIA GeForce GTX 1080 Ti
(vitis-ai-pytorch) Vitis-AI /workspace/models/AI-Model-Zoo/pt_fadnet_sceneflow_576_960_441G_2.0/code > ./run_demo.sh 
2022-06-02 07:04:24,794 [main.py:99] INFO Torch version: 1.4.0
2022-06-02 07:04:24,798 [main.py:100] INFO CUDA available: False
2022-06-02 07:04:24,800 [main.py:137] INFO Configurations: Namespace(augment=0, batch_size=1, beta=0.999, cuda=True, datapath='../data', dataset='sceneflow', demo=1, devices='0', eval=1, flowDiv=1.0, logFile='logs/fadnet_sceneflow_test_demo.log', loss='loss_configs/test.json', lr=0.0002, manualSeed=None, maxdisp=-1, model='../float/model_best_single.pth', momentum=0.9, net='fadnet', outf='.', showFreq=100, startEpoch=0, startRound=0, trainlist='lists/SceneFlow.list', vallist='lists/FlyingThings3D_release_TEST.list', workers=8)
2022-06-02 07:04:24,800 [main.py:141] INFO Random Seed: 8645
2022-06-02 07:04:24,802 [main.py:47] INFO [[0.32, 0.16, 0.08, 0.04, 0.02, 0.01, 0.005]]
2022-06-02 07:04:24,808 [dltrainer.py:66] INFO Use 16 processes to load data...
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=50 error=100 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "main.py", line 149, in <module>
    main(opt)
  File "main.py", line 50, in main
    trainer = DisparityTrainer(opt.net, opt.lr, opt.devices, opt.dataset, opt.trainlist, opt.vallist, opt.datapath, opt.batch_size, opt.maxdisp, opt.demo, opt.model)
  File "/workspace/models/AI-Model-Zoo/pt_fadnet_sceneflow_576_960_441G_2.0/code/dltrainer.py", line 53, in __init__
    self.initialize()
  File "/workspace/models/AI-Model-Zoo/pt_fadnet_sceneflow_576_960_441G_2.0/code/dltrainer.py", line 115, in initialize
    self._build_net()
  File "/workspace/models/AI-Model-Zoo/pt_fadnet_sceneflow_576_960_441G_2.0/code/dltrainer.py", line 90, in _build_net
    self.net.cuda()
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 304, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 223, in _apply
    param_applied = fn(param)
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 304, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/vitis-ai-user/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 197, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:50

```

**Comment by haipnh** [comment]
Take a look in the `run_demo.sh` and set `CUDA_VISIBLE_DEVICES=0`, the problem is solved.
However, it will show error `RuntimeError: CUDNN_STATUS_EXECUTION_FAILED` if RTX30 is being used.
In that case, manually install pytorch with CUDA 11-supported, instead of installing requirements.txt.
```
pip install --user scikit-image OpenEXR==1.3.2
pip install --user torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
```
